#!/usr/bin/env python3
"""
GlobePulse Security Report Generator
====================================
Formats, aggregates, and outputs security analysis findings into Markdown documents,
JSON data files, and formatted terminal output.
"""

import json
import os
import time
from typing import List, Dict, Any
from secret_scanner import Finding

class ReportGenerator:
    """Consolidates findings and produces Markdown, JSON, and terminal console reports."""

    def __init__(self, findings: List[Finding], output_dir: str = "security/reports"):
        self.findings = findings
        self.output_dir = os.path.abspath(output_dir)
        os.makedirs(self.output_dir, exist_ok=True)
        self.timestamp = time.strftime("%Y%m%d_%H%M%S")

    def count_by_severity(self) -> Dict[str, int]:
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for f in self.findings:
            sev = f.severity.upper()
            if sev in counts:
                counts[sev] += 1
            else:
                counts["LOW"] += 1
        return counts

    def generate_json(self) -> str:
        """Generate structured JSON report."""
        counts = self.count_by_severity()
        report_data = {
            "title": "GlobePulse Security Analysis Report",
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime()),
            "summary": {
                "total_findings": len(self.findings),
                "critical": counts["CRITICAL"],
                "high": counts["HIGH"],
                "medium": counts["MEDIUM"],
                "low": counts["LOW"]
            },
            "findings": [f.to_dict() for f in self.findings]
        }

        filename = f"security_report_{self.timestamp}.json"
        filepath = os.path.join(self.output_dir, filename)
        latest_path = os.path.join(self.output_dir, "latest_report.json")

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=2)

        with open(latest_path, "w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=2)

        return filepath

    def generate_markdown(self, pass_threshold: str = "HIGH") -> str:
        """Generate human-readable Markdown report."""
        counts = self.count_by_severity()
        critical_high = counts["CRITICAL"] + counts["HIGH"]
        status_badge = "FAILED" if critical_high > 0 else "PASSED"

        lines = []
        lines.append("# GlobePulse Security Audit Report")
        lines.append(f"**Generated At**: `{time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}`")
        lines.append(f"**Overall Compliance Status**: `{status_badge}` (Fail threshold: `{pass_threshold}`)")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append("")
        lines.append("| Severity Level | Count | Action Required |")
        lines.append("| :--- | :--- | :--- |")
        lines.append(f"| **CRITICAL** | `{counts['CRITICAL']}` | Immediate resolution required (< 24 hrs) |")
        lines.append(f"| **HIGH** | `{counts['HIGH']}` | Resolution required before merge (< 48 hrs) |")
        lines.append(f"| **MEDIUM** | `{counts['MEDIUM']}` | Address in current sprint (< 7 days) |")
        lines.append(f"| **LOW** | `{counts['LOW']}` | General maintenance backlog |")
        lines.append(f"| **TOTAL** | `{len(self.findings)}` | |")
        lines.append("")

        if not self.findings:
            lines.append("> [!NOTE]")
            lines.append("> No security vulnerabilities or policy violations were detected across the codebase.")
        else:
            lines.append("## Detailed Vulnerability Breakdown")
            lines.append("")
            grouped = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": []}
            for f in self.findings:
                sev = f.severity.upper()
                if sev in grouped:
                    grouped[sev].append(f)
                else:
                    grouped["LOW"].append(f)

            for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
                items = grouped[sev]
                if not items:
                    continue
                lines.append(f"### {sev} Findings ({len(items)})")
                lines.append("")
                for idx, f in enumerate(items, start=1):
                    lines.append(f"#### {idx}. [{f.rule_id}] {f.description}")
                    lines.append(f"- **Scanner**: `{f.scanner}`")
                    lines.append(f"- **Location**: `{f.file_path}:{f.line_number}`")
                    lines.append(f"- **Snippet**: `{f.snippet}`")
                    lines.append(f"- **Remediation**: {f.recommendation}")
                    lines.append("")

        lines.append("---")
        lines.append("*Report automatically generated by GlobePulse Security Framework.*")

        content = "\n".join(lines)
        filename = f"security_report_{self.timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)
        latest_path = os.path.join(self.output_dir, "latest_report.md")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        with open(latest_path, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath

    def print_terminal_summary(self, pass_threshold: str = "HIGH") -> bool:
        """Print colorized summary table to terminal and return pass/fail boolean."""
        counts = self.count_by_severity()
        RED = "\033[91m"
        YELLOW = "\033[93m"
        GREEN = "\033[92m"
        CYAN = "\033[96m"
        BOLD = "\033[1m"
        RESET = "\033[0m"

        print(f"\n{BOLD}{CYAN}===================================================={RESET}")
        print(f"{BOLD}{CYAN}      GLOBEPULSE SECURITY AUDIT SUMMARY             {RESET}")
        print(f"{BOLD}{CYAN}===================================================={RESET}\n")

        print(f"{BOLD}Severity Counts:{RESET}")
        print(f"  {RED}CRITICAL{RESET} : {counts['CRITICAL']}")
        print(f"  {RED}HIGH    {RESET} : {counts['HIGH']}")
        print(f"  {YELLOW}MEDIUM  {RESET} : {counts['MEDIUM']}")
        print(f"  {GREEN}LOW     {RESET} : {counts['LOW']}")
        print(f"  {BOLD}TOTAL   {RESET} : {len(self.findings)}\n")

        # Determine pass/fail based on fail_on threshold
        fail = False
        threshold_map = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1}
        target_val = threshold_map.get(pass_threshold.upper(), 3)

        for f in self.findings:
            sev_val = threshold_map.get(f.severity.upper(), 1)
            if sev_val >= target_val:
                fail = True
                break

        if fail:
            print(f"{BOLD}{RED}[RESULT] AUDIT FAILED - Security findings met or exceeded threshold '{pass_threshold}'{RESET}")
        else:
            print(f"{BOLD}{GREEN}[RESULT] AUDIT PASSED - No security findings met threshold '{pass_threshold}'{RESET}")

        print(f"\n{BOLD}Reports generated in '{self.output_dir}':{RESET}")
        print(f"  - Markdown: latest_report.md")
        print(f"  - JSON    : latest_report.json\n")

        return not fail

if __name__ == "__main__":
    gen = ReportGenerator([])
    gen.generate_markdown()
    gen.generate_json()
    gen.print_terminal_summary()
